name: native_view
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: native_view_android
      ios:
        default_package: native_view_ios


dependencies:
  flutter:
    sdk: flutter
  native_view_android:
    path: ../native_view_android
  native_view_ios:
    path: ../native_view_ios
  native_view_platform_interface:
    path: ../native_view_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

